name: Build APK

on:
  push:
    branches: [ "main" ]   # ← dispara em todo push na branch main
  workflow_dispatch:        # ← adiciona botão Run workflow

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

- name: Instalar dependências (Windows)
  run: |
    pip install --upgrade pip
    pip install cython==0.29.36
    pip install buildozer
    pip install kivy==2.3.0
    pip install kivymd==1.1.1

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: violao-com-ed-apk
          path: bin/*.apk
